SYNTAX FOR PROJECTION :

SELECT * [DISTINCT],COL_NAME/EXPRESSION [ALIAS]
FROM TABLE_NAME;

WHERE "DISTINCT" IS USED TO SELECT NON-REPETITIVE VALUES AND "ALIAS" IS GIVEN TO RENAME THE COLUMN NAME IN THE RESULT TABLE.