SELECTION : IT IS USED TO RETRIVE THE DATA BYS SELECTING BOTH "ROWS" AND "COLUMNS"

SELECT * [DISTINCT],COL_NAME/EXPRESSION [ALIAS]
FROM TABLE_NAME
WHERE <FILTER_CONDITION>

WHERE CLAUSE : 
-> IT IS USED TO FILTER THE RECORDS.
-> IT EXECUTED ROW BY ROW.
-> WE CANNOT PASS MULTI ROW FUNCTIONS.


